=== eirik1502/sol_champ/sol_engine/src/main/resources/worldConfigSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "title": "World configurations",
  "description": "Configurations of the world",

  "type": "object",
  "additionalProperties": false,

  "properties": {

    "compSysPackages": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },

    "componentSystems": {
      "description": "The componentSystems used in the world",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },

    "entityClasses": {
      "description": "The entity classes in the world that entities may use",
      "type": "array",
      "items": {
        "description": "Entity classes",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "className": {
            "description": "the name of the class",
            "type": "string"
          },
          "extendsClasses": {
            "description": "The name of the classes that this class extends",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "components": {
            "description": "The components of this entity class",
            "$ref": "#/definitions/components"
          }
        },
        "required": [
          "className"
        ]
      }
    },
    "initialEntities": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string"
          },
          "useClass": {
            "type": "string"
          },
          "overrideComponents": {
            "$ref": "#/definitions/components"
          }
        },
        "required": ["name", "useClass"]
      }
    }
  },

  "definitions": {

    "components": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/component"
      }
    },

    "component": {
      "type": "object",
      "properties": {

        "type": {
          "type": "string"
        },
        "values": {
          "type": "object"
        }

      },
      "required": ["type"],
      "additionalProperties": false
    }

  }

}

=== eirik1502/sol_champ/sol_engine/src/test/resources/worldConfigTest.json
{
  "compSysPackages": [
    "sol_engine",
    "sol_engine.loaders"
  ],
  "componentSystems": [
    "TestSys1",
    "TestSys2"
  ],
  "entityClasses": [
    {
      "className": "character",
      "components": [
        {"type": "TestPosComp"}
      ]
    },
    {
      "className": "frank",
      "extendsClasses": ["character"],
      "components": [
        {"type": "TestPosComp", "values": {"x": 100, "y": 100}}
      ]
    },
    {
      "className": "bill",
      "extendsClasses": ["frank", "character"],
      "components": [
        {"type": "TestTextComp", "values": {"text": "hello there"}},
        {"type": "TestPosComp"}
      ]
    }
  ],

  "initialEntities": [
    {
      "useClass": "frank",
      "name": "Frank1",
      "overrideComponents": []
    },
    {
      "useClass": "frank",
      "name": "Frank2",
      "overrideComponents": [
        {"type": "TestPosComp", "values": {"x":  300}}
      ]
    }
  ]
}
